version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      # for development: uncomment to mount source
      # - ./:/app
    restart: unless-stopped
